export const ADDED_TO_CART = "ADDED_TO_CART";
export const REMOVED_FROM_CART = "REMOVED_FROM_CART";

export const CART_LOADED_SUCCESS = "CART_LOADED_SUCCESS";
export const CART_LOADED_FAIL = "CART_LOADED_FAIL";

export const INCREMENT_QUANTITY = "INCREMENT_QUANTITY";
export const DECREMENT_QUANTITY = "DECREMENT_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
