import Head from "next/head";
import Image from "next/image";
import HeroImg from "../assets/hero-img.jpg";
import ProductCard from "../components/ProductCard";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Next Shoes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="hero flex flex-col md:flex-row md:items-end bg-[#EDECE1] p-10">
        <div className="h-auto w-full md:order-2">
          <Image
            src={HeroImg}
            alt="hero"
            className="object-cover h-full w-full"
          />
        </div>
        <div className="z-10 p-4">
          <h1 className="text-xl font-semibold">
            YEEZY BOOST 350 V2 ONYX AND BONE
          </h1>
          <button className="btn-black-outlined mt-4">FIND OUT MORE</button>
        </div>
      </section>

      <section className="newProducts p-4">
        <div className="flex flex-wrap justify-between items-center">
          <span className="text-lg font-semibold">NEW ARRIVALS</span>
          <button className="btn-black-outlined">VIEW ALL</button>
        </div>
        <div className="grid grid-cols-2 gap-4">
          <ProductCard />
        </div>
      </section>
    </div>
  );
}
