import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { useState } from "react";
import HeroImg from "../assets/hero-img.jpg";
import ProductCard from "../components/ProductCard";
import { HiArrowRight } from "react-icons/hi";

import products from "../dummyData";

export default function Home() {
  const [newProducts, setnewProducts] = useState(products);
  return (
    <div className="">
      <Head>
        <title>Next Shoes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="hero flex flex-col md:flex-row md:items-end bg-[#EDECE1] p-10">
        <div className="h-auto w-full md:order-2">
          <Image
            src={HeroImg}
            alt="hero"
            className="object-cover h-full w-full"
          />
        </div>
        <div className="z-10 p-4">
          <h1 className="text-xl font-semibold">
            YEEZY BOOST 350 V2 ONYX AND BONE
          </h1>
          <Link href="/products">
            <button className="btn-black-outlined mt-4">FIND OUT MORE</button>
          </Link>
        </div>
      </section>

      <section className="newProducts p-4 md:p-10">
        <div className="flex flex-wrap justify-between items-center pb-4">
          <span className="text-lg font-semibold">NEW ARRIVALS</span>
          <Link href="/products">
            <button className="btn-black-outlined flex items-center gap-2">
              VIEW ALL
              <HiArrowRight />
            </button>
          </Link>
        </div>
        <div className="grid grid-cols-2 gap-4 md:grid-cols-4 md:gap-3 ">
          {newProducts.map((product) => (
            <ProductCard key={product.id} product={product} />
          ))}
        </div>
      </section>
    </div>
  );
}
