import Head from "next/head";
import Card from "../components/Card";
import products from "../dummyData";

export default function Home() {
  return (
    <div className="md:px-10">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-2 gap-3 md:grid-cols-4 p-4">
        {products.map((product) => (
          <Card key={product.id} product={product} />
        ))}
      </div>
    </div>
  );
}
